(() => {
  "use strict";
  const GAME_ID=21216;
  const FEATURES=["gep_internal","match","match_info","rank","team","me","phase"];
  const listeners=new Set(); let dashboardId=null,featureTimer=null,ingestTimer=null,enrichTimer=null;
  const state={
    app:{version:"0.2.0",backendUrl:cleanUrl(window.MATCHINTEL_CONFIG?.backendUrl||"http://localhost:8080"),deviceId:"",lastError:null},
    auth:{accessToken:localStorage.getItem("mi.access")||"",refreshToken:localStorage.getItem("mi.refresh")||"",license:safeJson(localStorage.getItem("mi.license")),authenticated:false},
    game:{running:false,focused:false,eventHealth:"waiting",supportedFeatures:[],sessionId:null,matchId:null,pseudoMatchId:null,mode:null,region:null,isLive:false,startedAt:null,endedAt:null,totalPlayers:null,totalTeams:null,rank:null,localPlayerName:null,players:[],events:[],rawInfo:{},rawEvents:[],updatedAt:null},
    enrichment:{},settings:{playerName:localStorage.getItem("mi.playerName")||"",pinMyTeam:localStorage.getItem("mi.pinMyTeam")!=="false",moveDeadDown:localStorage.getItem("mi.moveDeadDown")!=="false",performanceMode:localStorage.getItem("mi.performanceMode")==="true"}
  };
  function cleanUrl(v){return String(v||"").trim().replace(/\/+$/,"")}
  function safeJson(v){try{return v?JSON.parse(v):null}catch{return null}}
  function parse(v){if(typeof v!=="string")return v;const t=v.trim();if(!t)return v;try{return (t[0]==="{"||t[0]==="[")?JSON.parse(t):v}catch{return v}}
  function clone(){return JSON.parse(JSON.stringify(state))}
  function notify(){const x=clone();for(const fn of listeners)try{fn(x)}catch(e){console.error(e)}}
  function subscribe(fn){listeners.add(fn);fn(clone());return()=>listeners.delete(fn)}
  function hash(text){text=JSON.stringify(text);let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
  function isFortnite(g){return !!g?.isRunning&&Math.floor(Number(g.classId)/10)===GAME_ID}
  function getDevice(){return new Promise(resolve=>overwolf.profile.getCurrentUser(r=>{const id=r?.machineId||r?.userId||localStorage.getItem("mi.fallbackDevice")||crypto.randomUUID();localStorage.setItem("mi.fallbackDevice",id);resolve(id)}))}
  function openDashboard(){overwolf.windows.obtainDeclaredWindow("dashboard",r=>{if(!r?.success){state.app.lastError=r?.error||"Cannot obtain dashboard";notify();return}dashboardId=r.window.id;overwolf.windows.restore(dashboardId,()=>{})})}
  function toggleDashboard(){if(!dashboardId)return openDashboard();overwolf.windows.getWindowState(dashboardId,r=>{if(r?.window_state==="normal"||r?.window_state==="maximized")overwolf.windows.minimize(dashboardId,()=>{});else overwolf.windows.restore(dashboardId,()=>{})})}
  function gameChanged(g){state.game.running=isFortnite(g);state.game.focused=!!g?.isInFocus;if(state.game.running){state.game.eventHealth="connecting";setFeatures()}else{state.game.eventHealth="waiting";state.game.isLive=false}notify()}
  function setFeatures(){clearTimeout(featureTimer);overwolf.games.events.setRequiredFeatures(FEATURES,r=>{if(r?.success){state.game.eventHealth="connected";state.game.supportedFeatures=r.supportedFeatures||FEATURES;state.app.lastError=null;overwolf.games.events.getInfo(x=>x?.success&&applyInfo(x.info||{}));notify()}else{state.game.eventHealth="retrying";state.app.lastError=`GEP: ${r?.error||"feature registration failed"}`;notify();featureTimer=setTimeout(setFeatures,4000)}})}
  function rosterKey(name){return /^roster(?:_|$)/i.test(name)}
  function playerFrom(value,key){const p=parse(value)||{},name=String(p.player||p.name||p.nickname||`Player ${key}`),team=p.team_id??p.teamId??null,local=!!(p.is_local??p.isLocal);return{key:String(p.account_id||p.accountId||`${team??"unknown"}:${name.toLowerCase()}`),displayName:name,accountId:p.account_id||p.accountId||null,teamId:team==null?null:String(team),isAlive:p.is_alive==null?true:!!p.is_alive,isLocal:local,kills:Number(p.kills||0),raw:p}}
  function mergePlayer(p){const i=state.game.players.findIndex(x=>x.key===p.key);if(i>=0)state.game.players[i]={...state.game.players[i],...p,raw:{...state.game.players[i].raw,...p.raw}};else state.game.players.push(p);if(p.isLocal)state.game.localPlayerName=p.displayName}
  function applyInfo(info){state.game.rawInfo={...state.game.rawInfo,...info};for(const [category,values0] of Object.entries(info||{})){const values=parse(values0)||{};if(typeof values!=="object")continue;for(const [key,value0] of Object.entries(values)){const value=parse(value0);if(rosterKey(key)){mergePlayer(playerFrom(value,key));continue}const k=key.toLowerCase();if(k==="sessionid")state.game.sessionId=String(value);else if(k==="matchid")state.game.matchId=String(value);else if(k==="pseudo_match_id")state.game.pseudoMatchId=String(value);else if(k==="mode")state.game.mode=String(value);else if(k==="total_players")state.game.totalPlayers=Number(value);else if(k==="total_teams")state.game.totalTeams=Number(value);else if(k==="rank")state.game.rank=Number(value);else if(category==="me"&&k==="name")state.game.localPlayerName=String(value);else if(k==="server"||k==="region")state.game.region=String(value)}}state.game.updatedAt=new Date().toISOString();scheduleEnrich();scheduleIngest();notify()}
  function parseFeed(text){text=String(text||"");let m=/^(.+?) eliminated (.+?)(?: \((\d+)\))? with (?:an? )?(.+?)(?: \((\d+) m\))?$/i.exec(text);if(m)return{actor:m[1],victim:m[2],teamId:m[3]||null,weapon:m[4]||null,description:text};m=/^(.+?) knocked (.+?)(?: \((\d+)\))?/i.exec(text);if(m)return{actor:m[1],victim:m[2],teamId:m[3]||null,description:text};return{description:text}}
  function addEvent(name,data){const now=new Date().toISOString(),parsed=parse(data),feed=name==="message_feed"?parseFeed(parsed):{},type=name==="generic"?String(parsed||"generic"):name,event={id:hash({name,data,sec:Math.floor(Date.now()/1000)}),type,actor:feed.actor||null,victim:feed.victim||null,teamId:feed.teamId||null,weapon:feed.weapon||null,occurredAt:now,description:feed.description||String(parsed?.description||parsed?.message||parsed||name),raw:parsed};if(state.game.events.some(x=>x.id===event.id))return;state.game.events.push(event);state.game.rawEvents.push({name,data:parsed,occurredAt:now});if(state.game.events.length>500)state.game.events.splice(0,state.game.events.length-500);if(state.game.rawEvents.length>1000)state.game.rawEvents.splice(0,state.game.rawEvents.length-1000);if(name==="matchStart"){state.game.isLive=true;state.game.startedAt=now;state.game.endedAt=null}if(name==="matchEnd"){state.game.isLive=false;state.game.endedAt=now}if(event.victim&&/(eliminated|death|killed)/i.test(event.description+" "+type)){const p=state.game.players.find(x=>x.displayName.toLowerCase()===event.victim.toLowerCase());if(p)p.isAlive=false}state.game.updatedAt=now;scheduleIngest();notify()}
  function onEvents(r){for(const e of r?.events||[])addEvent(e.name||"event",e.data)}
  function scheduleIngest(){clearTimeout(ingestTimer);if(!state.auth.accessToken||!state.game.sessionId)return;ingestTimer=setTimeout(()=>ingest().catch(fail),1500)}
  function scheduleEnrich(){clearTimeout(enrichTimer);if(!state.game.players.length)return;enrichTimer=setTimeout(()=>enrich().catch(fail),900)}
  async function request(path,options={},retry=true){const headers={"Content-Type":"application/json",...(options.headers||{})};if(state.auth.accessToken)headers.Authorization=`Bearer ${state.auth.accessToken}`;const r=await fetch(state.app.backendUrl+path,{...options,headers}),text=await r.text(),body=text?safeJson(text)||{message:text}:null;if(r.status===401&&retry&&state.auth.refreshToken&&await refresh())return request(path,options,false);if(!r.ok){const e=new Error(body?.message||`HTTP ${r.status}`);e.code=body?.code||`HTTP_${r.status}`;throw e}return body}
  async function activate(key){const x=await request("/v1/licenses/activate",{method:"POST",body:JSON.stringify({licenseKey:key,deviceId:state.app.deviceId,deviceName:`${navigator.platform} • Overwolf`,appVersion:state.app.version})},false);saveAuth(x);return x}
  function saveAuth(x){state.auth={accessToken:x.accessToken,refreshToken:x.refreshToken,license:x.license,authenticated:true};localStorage.setItem("mi.access",x.accessToken);localStorage.setItem("mi.refresh",x.refreshToken);localStorage.setItem("mi.license",JSON.stringify(x.license));notify()}
  async function refresh(){try{const r=await fetch(state.app.backendUrl+"/v1/auth/refresh",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({refreshToken:state.auth.refreshToken,deviceId:state.app.deviceId})});if(!r.ok)return false;saveAuth(await r.json());return true}catch{return false}}
  async function validate(){if(!state.auth.accessToken)return false;try{const x=await request("/v1/licenses/status");state.auth.license=x.license;state.auth.authenticated=true;notify();return true}catch{logout();return false}}
  function logout(){state.auth={accessToken:"",refreshToken:"",license:null,authenticated:false};localStorage.removeItem("mi.access");localStorage.removeItem("mi.refresh");localStorage.removeItem("mi.license");notify()}
  async function enrich(){if(!state.auth.accessToken)return;const names=[...new Set(state.game.players.map(x=>x.displayName).filter(x=>x&&!/^anonymous/i.test(x)))];if(!names.length)return;const x=await request("/v1/enrichment/players",{method:"POST",body:JSON.stringify({names})});for(const p of x.players||[])state.enrichment[String(p.displayName).toLowerCase()]=p;notify();scheduleIngest()}
  async function ingest(){if(!state.game.sessionId||!state.auth.accessToken)return;return request("/v1/live/ingest",{method:"POST",body:JSON.stringify({sessionId:state.game.sessionId,matchId:state.game.matchId,pseudoMatchId:state.game.pseudoMatchId,mode:state.game.mode,region:state.game.region,isLive:state.game.isLive,startedAt:state.game.startedAt,endedAt:state.game.endedAt,totalPlayers:state.game.totalPlayers,totalTeams:state.game.totalTeams,localPlayerName:state.game.localPlayerName,sourceUpdatedAt:state.game.updatedAt,players:state.game.players.map(p=>({...p,powerRanking:state.enrichment[p.displayName.toLowerCase()]?.powerRanking??null,lifetimeEarnings:state.enrichment[p.displayName.toLowerCase()]?.lifetimeEarnings??null})),events:state.game.events.slice(-150),rawInfo:state.game.rawInfo})})}
  function updateSettings(x){state.settings={...state.settings,...x};for(const [k,v] of Object.entries(state.settings))localStorage.setItem(`mi.${k}`,String(v));notify()}
  function updateBackendUrl(url){state.app.backendUrl=cleanUrl(url);localStorage.setItem("mi.backendUrl",state.app.backendUrl);logout()}
  function fail(e){console.error(e);state.app.lastError=`${e.code||"ERROR"}: ${e.message||e}`;notify()}
  overwolf.games.events.onInfoUpdates2.addListener(r=>{if(r?.info)applyInfo(r.info);else if(r?.category&&r?.key)applyInfo({[r.category]:{[r.key]:r.value}});});overwolf.games.events.onNewEvents.addListener(onEvents);overwolf.games.events.onError.addListener(e=>{state.game.eventHealth="error";state.app.lastError=JSON.stringify(e);notify()});overwolf.games.onGameInfoUpdated.addListener(r=>gameChanged(r?.gameInfo));overwolf.settings.hotkeys.onPressed.addListener(e=>e?.name==="toggle_dashboard"&&toggleDashboard());
  window.matchIntel={getState:clone,subscribe,openDashboard,toggleDashboard,activateLicense:activate,validateSession:validate,logout,ingestSnapshot:ingest,enrichPlayers:enrich,getHistory:()=>request("/v1/sessions"),getReport:()=>request("/v1/reports/summary"),updateSettings,updateBackendUrl};
  (async()=>{state.app.deviceId=await getDevice();const saved=localStorage.getItem("mi.backendUrl");if(saved)state.app.backendUrl=cleanUrl(saved);overwolf.extensions.current.getManifest(m=>{if(m?.meta?.version)state.app.version=m.meta.version});overwolf.games.getRunningGameInfo2(r=>gameChanged(r?.gameInfo));await validate();notify();openDashboard()})().catch(fail);
})();
