import { query,tx } from "./db.js";
import { config } from "./config.js";
import { createLicenseKey,parseDuration,randomUuid,sha256 } from "./security.js";
async function audit(action,actor,target,details){await query("INSERT INTO audit_logs(id,action,actor,target,details) VALUES($1,$2,$3,$4,$5)",[randomUuid(),action,String(actor).slice(0,200),String(target).slice(0,300),details])}
export async function create(req,res){try{const duration=req.body?.duration||"30d",key=createLicenseKey(),l={id:randomUuid(),plan:String(req.body?.plan||"pro").slice(0,50),expiresAt:parseDuration(duration),maxDevices:Math.max(1,Math.min(25,Number(req.body?.maxDevices||1))),features:Array.isArray(req.body?.features)?req.body.features.map(String).slice(0,40):["live_lobby","enrichment","history","reports"],note:String(req.body?.note||"").slice(0,500)};await query(`INSERT INTO licenses(id,key_hash,key_prefix,plan,expires_at,max_devices,features,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[l.id,sha256(key),key.slice(0,12),l.plan,l.expiresAt,l.maxDevices,JSON.stringify(l.features),l.note]);await audit("license.create",req.headers["x-admin-actor"]||"admin",l.id,{duration,plan:l.plan});res.status(201).json({licenseKey:key,license:l})}catch(error){res.status(400).json({code:"MI-ADMIN-LICENSE",message:error.message})}}
export async function find(req,res){const q=String(req.query.q||"").trim(),r=await query(`SELECT l.*,(SELECT COUNT(*)::int FROM devices d WHERE d.license_id=l.id) device_count FROM licenses l WHERE $1='' OR l.id::text ILIKE '%'||$1||'%' OR l.key_prefix ILIKE '%'||$1||'%' OR COALESCE(l.note,'') ILIKE '%'||$1||'%' ORDER BY l.created_at DESC LIMIT 100`,[q]);res.json({licenses:r.rows})}
export async function revoke(req,res){const r=await query("UPDATE licenses SET status='revoked',updated_at=NOW() WHERE id=$1 RETURNING *",[req.params.id]);if(!r.rowCount)return res.status(404).json({code:"MI-LICENSE-NOT-FOUND",message:"License not found."});await query("UPDATE refresh_tokens SET revoked_at=NOW() WHERE license_id=$1 AND revoked_at IS NULL",[req.params.id]);await audit("license.revoke",req.headers["x-admin-actor"]||"admin",req.params.id,{});res.json({license:r.rows[0]})}
export async function reset(req,res){await tx(async c=>{await c.query("DELETE FROM devices WHERE license_id=$1",[req.params.id]);await c.query("UPDATE refresh_tokens SET revoked_at=NOW() WHERE license_id=$1 AND revoked_at IS NULL",[req.params.id])});await audit("license.reset_devices",req.headers["x-admin-actor"]||"admin",req.params.id,{});res.json({ok:true})}
export async function maintenance(req,res){const enabled=!!req.body?.enabled,message=String(req.body?.message||config.maintenanceMessage).slice(0,500);await query(`INSERT INTO app_settings(key,value) VALUES('maintenance',$1) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=NOW()`,[JSON.stringify({enabled,message})]);await audit("system.maintenance",req.headers["x-admin-actor"]||"admin","maintenance",{enabled,message});res.json({enabled,message,note:"Set MAINTENANCE_MODE on Railway for startup-level enforcement."})}
export async function status(req,res){const [a,b,c]=await Promise.all([query("SELECT COUNT(*)::int count FROM licenses WHERE status='active' AND (expires_at IS NULL OR expires_at>NOW())"),query("SELECT COUNT(*)::int count FROM devices"),query("SELECT COUNT(*)::int count FROM sessions")]);res.json({status:"ok",activeLicenses:a.rows[0].count,devices:b.rows[0].count,sessions:c.rows[0].count,version:config.latestAppVersion})}
