import { query,tx } from "./db.js";
import { randomUuid } from "./security.js";
const clean=(v,n=500)=>v==null?null:String(v).slice(0,n);
export async function ingest(req,res){
  const b=req.body||{};if(!b.sessionId)return res.status(400).json({code:"MI-SESSION-ID",message:"A session ID is required."});
  const result=await tx(async c=>{const found=await c.query("SELECT id FROM sessions WHERE session_id=$1 FOR UPDATE",[b.sessionId]),id=found.rows[0]?.id||randomUuid();
    await c.query(`INSERT INTO sessions(id,session_id,match_id,pseudo_match_id,mode,region,is_live,started_at,ended_at,total_players,total_teams,local_player_name,source_updated_at,snapshot,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,NOW()) ON CONFLICT(session_id) DO UPDATE SET match_id=EXCLUDED.match_id,pseudo_match_id=EXCLUDED.pseudo_match_id,mode=EXCLUDED.mode,region=EXCLUDED.region,is_live=EXCLUDED.is_live,started_at=COALESCE(sessions.started_at,EXCLUDED.started_at),ended_at=EXCLUDED.ended_at,total_players=EXCLUDED.total_players,total_teams=EXCLUDED.total_teams,local_player_name=EXCLUDED.local_player_name,source_updated_at=EXCLUDED.source_updated_at,snapshot=EXCLUDED.snapshot,updated_at=NOW()`,[id,b.sessionId,clean(b.matchId),clean(b.pseudoMatchId),clean(b.mode),clean(b.region),!!b.isLive,b.startedAt||null,b.endedAt||null,Number.isFinite(Number(b.totalPlayers))?Number(b.totalPlayers):null,Number.isFinite(Number(b.totalTeams))?Number(b.totalTeams):null,clean(b.localPlayerName),b.sourceUpdatedAt||null,b]);
    await c.query(`INSERT INTO session_access(session_id,license_id,device_hash) VALUES($1,$2,$3) ON CONFLICT(session_id,license_id,device_hash) DO UPDATE SET last_seen_at=NOW()`,[id,req.auth.license.id,req.auth.deviceHash]);
    for(const p of b.players||[]){const key=clean(p.key||p.accountId||`${p.teamId}:${p.displayName}`);if(!key||!p.displayName)continue;await c.query(`INSERT INTO players(session_id,player_key,display_name,account_id,team_id,is_alive,kills,power_ranking,lifetime_earnings,raw,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,NOW()) ON CONFLICT(session_id,player_key) DO UPDATE SET display_name=EXCLUDED.display_name,account_id=COALESCE(EXCLUDED.account_id,players.account_id),team_id=EXCLUDED.team_id,is_alive=EXCLUDED.is_alive,kills=GREATEST(players.kills,EXCLUDED.kills),power_ranking=COALESCE(EXCLUDED.power_ranking,players.power_ranking),lifetime_earnings=COALESCE(EXCLUDED.lifetime_earnings,players.lifetime_earnings),raw=EXCLUDED.raw,updated_at=NOW()`,[id,key,clean(p.displayName),clean(p.accountId),clean(p.teamId,100),p.isAlive!==false,Number(p.kills||0),p.powerRanking??null,p.lifetimeEarnings??null,p.raw||p]);}
    for(const e of b.events||[]){const key=clean(e.id||`${e.type}:${e.occurredAt}:${e.actor}:${e.victim}`);if(!key)continue;await c.query(`INSERT INTO events(session_id,event_key,occurred_at,type,actor,victim,team_id,weapon,description,raw) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(session_id,event_key) DO NOTHING`,[id,key,e.occurredAt||new Date(),clean(e.type)||"event",clean(e.actor),clean(e.victim),clean(e.teamId,100),clean(e.weapon),clean(e.description,1000),e.raw||e]);}
    return{id};});req.app.locals.broadcast?.(b.sessionId,{type:"session_update",session:b});res.json({ok:true,sessionDatabaseId:result.id});
}
export async function list(req,res){const r=await query(`SELECT s.session_id,s.match_id,s.mode,s.region,s.is_live,s.started_at,s.ended_at,s.updated_at,COUNT(DISTINCT p.player_key)::int player_count,COUNT(DISTINCT e.event_key)::int event_count FROM sessions s JOIN session_access sa ON sa.session_id=s.id LEFT JOIN players p ON p.session_id=s.id LEFT JOIN events e ON e.session_id=s.id WHERE sa.license_id=$1 GROUP BY s.id ORDER BY s.updated_at DESC LIMIT 100`,[req.auth.license.id]);res.json({sessions:r.rows})}
export async function one(req,res){const r=await query(`SELECT s.snapshot FROM sessions s JOIN session_access sa ON sa.session_id=s.id WHERE s.session_id=$1 AND sa.license_id=$2 LIMIT 1`,[req.params.sessionId,req.auth.license.id]);if(!r.rowCount)return res.status(404).json({code:"MI-SESSION-NOT-FOUND",message:"Session not found."});res.json(r.rows[0].snapshot)}
