import {Client,GatewayIntentBits,REST,Routes,SlashCommandBuilder,EmbedBuilder} from "discord.js";
const need=n=>{const v=process.env[n];if(!v)throw new Error(`Missing ${n}`);return v},token=need("DISCORD_TOKEN"),clientId=need("DISCORD_CLIENT_ID"),guildId=need("DISCORD_GUILD_ID"),backend=need("BACKEND_URL").replace(/\/+$/,"");const adminKey=need("BACKEND_ADMIN_KEY"),owners=new Set(need("OWNER_DISCORD_IDS").split(",").map(x=>x.trim()));
const commands=[new SlashCommandBuilder().setName("key-create").setDescription("Create a MatchIntel key").addStringOption(o=>o.setName("duration").setDescription("7d, 30d, 1y, lifetime").setRequired(true)).addStringOption(o=>o.setName("plan").setDescription("Plan").setRequired(true)).addIntegerOption(o=>o.setName("devices").setDescription("Device limit").setMinValue(1).setMaxValue(25)).addStringOption(o=>o.setName("note").setDescription("Private note")),new SlashCommandBuilder().setName("key-revoke").setDescription("Revoke a key").addStringOption(o=>o.setName("license_id").setDescription("License UUID").setRequired(true)),new SlashCommandBuilder().setName("key-reset-devices").setDescription("Reset bound devices").addStringOption(o=>o.setName("license_id").setDescription("License UUID").setRequired(true)),new SlashCommandBuilder().setName("license-find").setDescription("Search licenses").addStringOption(o=>o.setName("query").setDescription("ID, prefix or note")),new SlashCommandBuilder().setName("maintenance").setDescription("Set maintenance state").addBooleanOption(o=>o.setName("enabled").setDescription("Enabled").setRequired(true)).addStringOption(o=>o.setName("message").setDescription("Message")),new SlashCommandBuilder().setName("system-status").setDescription("Show backend status")].map(x=>x.toJSON());
await new REST({version:"10"}).setToken(token).put(Routes.applicationGuildCommands(clientId,guildId),{body:commands});
const client=new Client({intents:[GatewayIntentBits.Guilds]});
async function api(path,options={}){const r=await fetch(backend+path,{...options,headers:{"Content-Type":"application/json","X-Admin-Key":adminKey,"X-Admin-Actor":options.actor||"discord-bot",...(options.headers||{})}}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||`HTTP ${r.status}`);return b}
const embed=(title,fields,color=0x168cff)=>new EmbedBuilder().setTitle(title).setColor(color).addFields(fields).setTimestamp();
client.on("interactionCreate",async i=>{if(!i.isChatInputCommand())return;if(!owners.has(i.user.id))return i.reply({content:"This command is restricted to MatchIntel owners.",ephemeral:true});await i.deferReply({ephemeral:true});try{if(i.commandName==="key-create"){const x=await api("/v1/admin/licenses",{method:"POST",actor:i.user.id,body:JSON.stringify({duration:i.options.getString("duration"),plan:i.options.getString("plan"),maxDevices:i.options.getInteger("devices")||1,note:i.options.getString("note")||""})});return i.editReply({embeds:[embed("MatchIntel key created",[{name:"Key",value:`\`${x.licenseKey}\``},{name:"License ID",value:`\`${x.license.id}\``},{name:"Plan",value:x.license.plan,inline:true},{name:"Devices",value:String(x.license.maxDevices),inline:true},{name:"Expires",value:x.license.expiresAt?new Date(x.license.expiresAt).toISOString():"Lifetime"}])]})}if(i.commandName==="key-revoke"){const id=i.options.getString("license_id");await api(`/v1/admin/licenses/${encodeURIComponent(id)}/revoke`,{method:"POST",actor:i.user.id});return i.editReply(`Revoked \`${id}\`.`)}if(i.commandName==="key-reset-devices"){const id=i.options.getString("license_id");await api(`/v1/admin/licenses/${encodeURIComponent(id)}/reset-devices`,{method:"POST",actor:i.user.id});return i.editReply(`Reset devices for \`${id}\`.`)}if(i.commandName==="license-find"){const x=await api(`/v1/admin/licenses?q=${encodeURIComponent(i.options.getString("query")||"")}`,{actor:i.user.id});return i.editReply(x.licenses.slice(0,15).map(l=>`\`${l.id}\` • **${l.plan}** • ${l.status} • ${l.device_count}/${l.max_devices} devices • ${l.key_prefix}…`).join("\n")||"No licenses found.")}if(i.commandName==="maintenance"){const x=await api("/v1/admin/maintenance",{method:"POST",actor:i.user.id,body:JSON.stringify({enabled:i.options.getBoolean("enabled"),message:i.options.getString("message")||undefined})});return i.editReply(`Maintenance is **${x.enabled?"enabled":"disabled"}**.\n${x.message}`)}if(i.commandName==="system-status"){const x=await api("/v1/admin/status",{actor:i.user.id});return i.editReply({embeds:[embed("MatchIntel system status",[{name:"Backend",value:x.status,inline:true},{name:"Version",value:x.version,inline:true},{name:"Active licenses",value:String(x.activeLicenses),inline:true},{name:"Devices",value:String(x.devices),inline:true},{name:"Sessions",value:String(x.sessions),inline:true}],0x41d56e)]})}}catch(e){await i.editReply(`Error: ${e.message}`)}});
client.once("ready",()=>console.log(`MatchIntel bot logged in as ${client.user.tag}`));client.login(token);
